INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3008, 'Admin', 'folder', CONVERT(DATETIME, '20160524', 101), 'Admin', 0)
INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3009, 'User1', 'folder', CONVERT(DATETIME, '20160524', 101), 'User1', 0)
INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3010, 'User2', 'folder', CONVERT(DATETIME, '20160524', 101), 'User2', 0)
INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3008, 'root', 'folder', CONVERT(DATETIME, '20160524', 101), 'Admin\root', 0)
INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3009, 'root', 'folder', CONVERT(DATETIME, '20160524', 101), 'User1\root', 0)
INSERT INTO MegaFileStorage.Files ([OwnerID], [FileName], [Extension], [UploadDate], [FullName], [AccessType])
VALUES(3010, 'root', 'folder', CONVERT(DATETIME, '20160524', 101), 'User2\root', 0)